### PR TITLE
skinny baby code

### PR DESCRIPTION
**Pull request by indarasuarez**
1.  Propose to remove a bunch of branches (commented in each file as "obsolete")
2.  Bools created to add in extra branches for studies
   if(filltaus)  Taus.SetBranches(BabyTree);
   
   if(filltracks)  Tracks.SetBranches(BabyTree);
   
   if(fillZll)  StopEvt.SetZllBranches(BabyTree);
   
   if(fillPhoton) StopEvt.SetPhotonBranches(BabyTree);
   
   if(fillMETfilt) StopEvt.SetMETFilterBranches(BabyTree);
   
   if(fill2ndlep) StopEvt.SetExtraVariablesBranches(BabyTree);
   
   if(fillExtraEvtVar) StopEvt.SetSecondLepBranches(BabyTree);
   
   if(fillAK4EF)   jets.SetAK4Branches_EF(BabyTree);
   
   if(fillAK4_Other)  jets.SetAK4Branches_Other(BabyTree);
   
   if(fillOverleps)  jets.SetAK4Branches_Overleps(BabyTree);
   
   if(fillAK4Synch)  jets.SetAK4Branches_SynchTools(BabyTree);
   
   if(fillElID)  lep1.SetBranches_electronID(BabyTree);
   
   if(fillIso)  lep1.SetBranches_Iso(BabyTree);
   
   if(fillLepSynch)  lep1.SetBranches_SynchTools(BabyTree);
   
   if(fillElID)  lep2.SetBranches_electronID(BabyTree);
   
   if(fillIso)  lep2.SetBranches_Iso(BabyTree);
   
   if(fillLepSynch)  lep2.SetBranches_SynchTools(BabyTree);
3.  Merging of some branches

3a.  Triggers -->  instead of one branch per trigger path, one branch per trigger type:
    int HLT_SingleMu;
    int HLT_SingleEl;
    int HLT_MET;
    int HLT_DiEl;
    int HLT_DiMu;
    int HLT_Photon;
    int HLT_MuE;

3b.  MET filters --> one single filt_met branch that includes all recommended met filters

3c.  lepton IDs:  passLooseID, passMediumID, passTightID instead of is_(ele/muo)id_loose ....

3d.  put gen_ts as part of gen_qs

### CODE REVIEW

**Comment by haweber** [comment]
I didn't run the code yet, but from just reviewing/reading it, here a bunch of comments - some might need clarifications for me, but there are also five bugs (out of which two were already in there :-/) - highlighted in bold:

general: 
- do not fully understand your fillXXX flags: take as example the fillPhoton one (encountered it first): If I understand the current logic correctly, this flag only prevents us from creating and filling those branches, correct? However, you still do all the computations - if we could drop those, we could save some CPU time.
  E.g. looper.C:l.202 prevents from creating branches in EventTree.cc:l.567, e.g. ph_selectedidx or ph_MT2W.
  But looper.C:l.1278 fills StopEvt.ph_selectedidx always, and consequently all other photon branches in l.1465ff. My suggestion would be to drop also the computation of that: For my example that would mean an if-clause around looper.C:l.1265-1278 and looper.C:l.1465-l.1545. If you want I can point out all those instances.
  _----->fine, I put them in but i didnt do it before because its not like this is the main cause of our problems_
- bsf and jecs are already stored in CORE. Can we switch to those - and also: we could add lepSF and jsons to CORE I guess and remove it from our looper. 
- Alternative - can we delete old files here - or better: make one name (like json_stop.txt), and update the file - else we will accumulate MB of data here, which is always pulled when you download the repository. 
  _-----> will do this later, not urgent_
- Finally we could merge/drop one of batch and batch_mia
  _-----> I let John and Mia sort this out.  I think most of us use "batch"_

runBabyMaker.C:
- should l.103-117 all be false? (I'm fine, just wondering if people agree with it)
  _----->for the first run yes, these extra branches are only meant to be stored for specific studies.  For the main analysis, setting them all to false should still give us results_
- should we have a issignal flag? We define issignal in looper.C and EventTree.C - we could make that more consistent between the two... (can do that later)
  _--------> i dont think this matters_

looper.C

**\- l.204/l.205: flags mixed up** _--> fixed_
- l.500/l.527: should add total lepSF weight to those histograms; also (I can do it after this pull request is done): split any fastsim/fullsim scale factor from global scale factor (currently this means splitting bSF SF into a fullsim/data and fastsim/fullsim SF)
  _----> I will let you take care of this_
- l.837: can we add charginos here - actually why not store all susy particles: abs(id)>=1000000&&abs(id)<=1000040
  _----> done_
- l.906: delete - isn't this a duplicate of l.905. Also: genlepsfromtop is not reset anymore in EventTree.cc:l.181 - please reset it again and add branch back again - I would delete in in genleps instead, same is true for genLepsHardProcess/genNusHardProcess: If we truly want to delete it (I don't know - you need to ask John about their usefulness), one needs to fix l.934/l.937
  _---> these do not need to be stored but they are used to create the is2lep, is1lep,... event tags_

l.1031 nlooseleps is "filled here", but branch is not reset in EventTree.cc, l.179 - I don't know if we want - to keep it or delete it completely (I drop those comments now - but it looks confusing to define all these variables but then not storing them see general comment)
_---> I don't know what nlooseleps is used for, so I've removed the branch all together_

**\- l.1580-1653: I think this is buggy now: you only store StopEvt.PassTrackVeto, we dropped the v2,v3 version. What we need to do here, is renamve the _v3 version and make it the default one, and delete old default and _v2 versions. same is true for isoTracks_isVetoTrack_v3 (actually we should also delete the functions like isVetoTrack_v3)**
_-->fixed_
- l.1714/1734/1745: I am not sure about one thing here, so just asking: we fill here genleps - but shouldn't this affect the flags define earlier in l.914-916
  _-->nope_

**\- l.1763 must be changed due to prescales! see usage
https://github.com/haweber/OneLepStop/blob/master/someMacros/PhotMETResolution.C#L267-L276
maybe a compromise could be store smallest int > 0 - that should be good enough for anything we do: we should be able to merge the photon trigger paths into one branch, but I think we can't avoid to hardcode the exact trigger names for prescaled trigger**
_-->went back to old photon triggers_
- l.1872: why are files only closed but not deleted - they all were initialized with "new TFile" - maybe use TFile::Open instead?
  _ -->hmmm, the code works as it is.  if you prefer this, I let you do it_

EventTree.cc:
- see looper.C about keeping/dropping branches l.668-671 (and all related changes)
  _--->please see relevant comments above_
- I would add l.678 into the group in l.549
  _---> The good vertex met filter is actually nvtxs (number of good vertexes) > 1, which is already required on the skim.  Also required on skim is firstGoodVtxIdx==0 (first vertex is good vertex), which is an analysis choice.  Don't understand why you would also need to store it in the baby._
- l.119: this doesn't do anything - is this intended?
  _---> yes_

EventTree.h: 
- all obsolete branches have still ints/floats define here, e.g.
  l.198-202 are only left here, but nowhere else - this is true for many branches - it is not a problem, but makes things more confusing - this is true for all other .h files  
  _--->fine, i've removed them_

IsoTracksTree.cc: 
- (maybe this fits better into the "looper.C" comments): make isVetoTrack_v3 --> isVetoTrack and drop other two. Also, shouldn't we make a selection here - we seem to store all tracks (within eta/pt), regardless of isolation ...
  _--->fixed.  kept all the isVetoTrack_v? but defined correct veto for what is stored in the baby
- l.33/34,48/49: These branches seem to be always empty, delete.
  _----> deleted_

JetTree.cc:
- l.143/l.155/l.191/l.223/311/312 make the btag name configurable - maybe from runBabyMaker, at least define it maybe once at the beginning here, such that it cannot happen that we mix things up, if we change the btag discriminator name
  _--->later_
- l.185-186, etc.: See previous comment in "looper.C" about calculating those variables if not stored - I guess it is less critical here, as here it is only filling
  _----> I am going to leave this alone for now, don't think it is critical_

**\- l.190: I think this one is wrong! - type1 correction can affect pfmet_phi. Drop variable?**
_---->variable dropped, the dphi_met_j1j2 is stored correctly
- l.192/195: duplicates - we should drop one of the two
  _-----> for now, i will leave as it is, I don't know what PU id we will end up using if we choose to use one so they are placeholders for now_
- l.228: should we drop this branch given l.317
  _---->228 is highest pT med tagged jet and 317 is highest CSV value jet, not the same_

**\- l.231: this line seems to be wrong - I actually think it made our Moriond result buggy! delete it.
as said - i want to separate fastsimBSF event weight uncertainty from the rest, but we can do this after this pull request has been completed.**
_----->since you took care of fastsim SFs, I will let you fix it_
- l.583: depending on trigger strategy we might need to move this one out to general - the lower MET threshold trigger requires a tight ID'd jet as far as I remember
  _can review later_
- l.563: can we move this one out - we need it for sure given the recent fastsim bug discussions - I guess just flip the flag when running on signal (if this is what you initially intended with those flags)
  _let you address it_

LeptonTree: 
- just for consistency I would change all lines such as l.32 to lines like l.34
- l.62: question: do we want to store ID points without isolation?? - I'm fine with what you have here, just want to check
  _I use them for mt studies but no one else does_

PhotonTree: 
- I guess we can skim that one too - I can do it after we completed this pull request

StopSelections.cc:
- clean that up after changes above: e.g. we can delete isVetoTrack_v2()
  _done_

TauTree:
- can we do a little cleanup here too? I think _mass and _charge are duplicated, given that we store _p4 and _ID
  _done_

additional suggestions: 
things to add for investigation purposes (I can do it later):
nloosebtags, MT2_l_l
- should we move histogram names etc outside of looper, i.e. changing somewhat l.374-446, l.467, l.547, l.560-578, l.609-619, same true for l.22ff in EventTree.cc - this is not essential
- JetTree.cc: question l.81: should we move BTAG_MED to runBabyMaker ? - it does not really matter - but maybe better organized ??

**Comment by haweber** [comment]
Actually John found this:
https://github.com/cmstas/StopAnalysis/blob/skinnybaby_7.4X_lepSF/StopBabyMaker/JetTree.cc#L240
should be pt() instead of eta()
_done_

**Comment by haweber** [comment]
I just looked to the changes.
From my point of view we could go ahead (merge the code), does someone else want to comment on it?

There is one issue that was not really fixed (but I can do that later with the other stuff Indara left for me:) ) - given the short timescale I would not wait right now for it:
The "went back to old photon triggers" is incomplete: The branches are not reset or even created:
EventTree.cc: L338ff and L652ff.

**Comment by jgwood3141** [comment]
Hi HJ and Indara,

 Just saw this latest fix:

https://github.com/cmstas/StopAnalysis/pull/4/commits/000cb6292481dae72f0652cfa8f8ed3d449254a1

I haven't tried running this, but if you just commented out the var, then
this won't run.  That var is used downstream.  Instead, it should be set
from the variable that already exist in runBabyMaker.C

**Comment by haweber** [comment]
Hi John

is fastsim is defined here:
https://github.com/cmstas/StopAnalysis/blob/000cb6292481dae72f0652cfa8f8ed3d449254a1/StopBabyMaker/JetTree.cc#L71

but it was overwritten
https://github.com/cmstas/StopAnalysis/blob/000cb6292481dae72f0652cfa8f8ed3d449254a1/StopBabyMaker/JetTree.cc#L231

I did not test it, but unless I am really wrong L231 should go out, and the isFastsim from L71 should be the one to use …

Cheers,
   Hannsjörg

**Comment by jgwood3141** [comment]
Hi all,

One more thing:

https://github.com/cmstas/StopAnalysis/blob/000cb6292481dae72f0652cfa8f8ed3d449254a1/StopBabyMaker/JetTree.cc#L81

https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation80X

If we are going to run over all 80x MC, it looks like the bTag WP has been
changed from 0.890 -> 0.80

**Comment by mialiu149** [comment]
Hi John, I see this branch is for 74x. I have updated sample.dat, jec and btagging WP etc to run on 80x.
I will wait for this branch to be merged before commit those development.

**Pull request merged**
